### ISSUE TITLE
Highlight for Reaction arrows works far from arrows and it can be selected and moved

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2569]
**Steps to Reproduce**
1. Open Ketcher
2. Add two Reaction arrows on canvas. One horizonal and one vertical.
3. Move cursor away from one of arrow on the side of arrow or other end of arrow
4. Move cursor strictly opposite arrow from any of its ends
5. Select the 'Selection tool' and also move cursor in distance from either end of arrow
6. Move cursor strictly opposite arrow from any of its ends and when arrow is highlight click and drag

**Actual behavior**
When moving cursor away from arrow and cursor is exactly opposite arrow, it is highlighted and it can be selected by clicking or moved by click and drag

**Expected behavior**
Highlight for arrow works only when you point directly at arrow. Also, moving the arrow is only possible by directly clicking on arrow and dragging it to a new position on canvas.

**Screenshots**

https://user-images.githubusercontent.com/62464241/235792385-7de9bcbe-d7f4-4c33-a96f-090df78b69ad.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ivanmaslow** [comment]
Pay attention, that this issue is also reproducible for simple object Shape Line:
![image](https://github.com/user-attachments/assets/8986f7e4-39d2-48af-94f9-40d82394f88d)

**Comment by ivanmaslow** [comment]
it will be fixed together with changes for Multi-Tailed Arrows https://github.com/epam/ketcher/issues/4861

**Comment by ivanmaslow** [comment]
It was tested on the nightly environment (5057-hover-selection) - it was fixed for arrows, but not for lines:

https://github.com/user-attachments/assets/b1203e76-79a9-4a92-a71c-f8fe34e8d082

**Comment by ivanmaslow** [comment]
It was retested on the nightly environment (5057-hover-selection) - it was fixed for arrows and line.

**Comment by Zhirnoff** [comment]
Tested. Bug partially fixed. Registered bug https://github.com/epam/ketcher/issues/5433


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
