### ISSUE TITLE
The prompt shows undefined eventBus

### ISSUE THREAD

**Issue by FreedomClannad** [epam/ketcher#2728]
After compiling with version 2.9.0, I put it in the project. After installing the official demo, I found that I kept reporting Cannot read properties of undefined (reading 'eventBus'). I found that it was in kethcer-react. Ask this How to solve it, my project uses react version 18.2.0.

![image](https://github.com/epam/ketcher/assets/34476893/7aa3d026-bf02-4b68-b1ba-bd9c2600d793)

**Comment by MahmoudHemaid** [comment]
@FreedomClannad Did you found a fix for this bug?

**Comment by MahmoudHemaid** [comment]
I fixed this issue by adding `(window as any).ketcher = ketcher;` in my own `onInit` function

**Comment by FreedomClannad** [comment]
> `(window as any).ketcher = ketcher;`我通过添加自己的`onInit`函数解决了这个问题
Mine didn't solve this problem. After I tested according to your test later, copying and pasting still didn't respond

**Comment by FreedomClannad** [comment]
@MahmoudHemaid Mine didn't solve this problem. After I tested according to your test later, copying and pasting still didn't respond

**Comment by FreedomClannad** [comment]
@MahmoudHemaid 
(global as any).ketcher = ketcher;
(window as any).ketcher = ketcher;
 in my own onInit function

**Comment by FreedomClannad** [comment]
@MahmoudHemaid After I tested it, I found that it cannot be used during development, but it can be used normally after packaging and compiling
