### ISSUE TITLE
Changing the export file format from the drop down leads to an error

### ISSUE THREAD

**Issue by sreichau** [epam/ketcher#6051]
**Steps to Reproduce**
1. Draw a structure
2. Click on "Save As"
3. In the dialog that opens, click on the file format drop down and select a different file format (for example CDX). 

**Actual behavior**
An error message

```
Error Message
Convert error! 'NoneType' object has no attribute 'loadMonomerLibrary'
```

is displayed and the selection in the drop down is still the default MDL Molfile V2000.

**Expected behavior**

- The file format selected in the drop down should be what was clicked on in the drop down
- The preview of the file should adapt to the selected format
- The structure should be able to be saved to a file in the selected format

**Screenshots**
![Screenshot 2024-12-04 at 10 00 42](https://github.com/user-attachments/assets/e5399b54-d201-46a8-80c3-0ab0d88b67d2)
![Screenshot 2024-12-04 at 10 01 01](https://github.com/user-attachments/assets/48155096-ba8e-4232-b019-d50aa809d317)
![Screenshot 2024-12-04 at 10 01 15](https://github.com/user-attachments/assets/5dad4b5b-69c3-4d9f-93e3-8efde32d688e)
![Screenshot 2024-12-04 at 10 01 25](https://github.com/user-attachments/assets/0c7e29d3-7493-4ca8-8ef6-9d72d9305f0e)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 131.0.6778.86 (Official Build) (x86_64)

**Ketcher version** 
2.26.0

**Test case**
not applicable

**Additional context**
not applicable

**Comment by d-mrzv** [comment]
@sreichau big is fixed

**Ketcher Version** 
3.2.0-rc.1
**Indigo Version**
1.30.0-rc.1.0
**Browser:** Google Chrome
**OS**: MacOS 15.3.1

**Comment by AlexeyGirin** [comment]
Verified.
![Image](https://github.com/user-attachments/assets/706e5c97-e4d5-427a-9fd1-f68dc788f652)

- Ketcher Version 3.2.0-rc.1 Build at 2025-03-04; 14:24:35
- Indigo Version 1.30.0-rc.1.0-g9bdedaba9-wasm32-wasm-clang-19.0.0
- Chrome Version 134.0.6998.36 (Official Build) (64-bit)
- Win10

**Comment by sreichau** [comment]
Thank you for the fix. It now works for me now for most selections from the drop down. However, only for RDF V2000 and RDF V3000 I still get a (different) error. See the attached video. 

https://github.com/user-attachments/assets/f8fef2e8-279a-4bfc-ac72-c5291ca31a6a
