### ISSUE TITLE
Antisense creation doesn't work for the chain if not eligable base present in other chain presented in selection

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6089]
**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{R(A)P.[dR](A+C+G+U)P.R(A)P}|RNA2{R(A)P.[dR](A)P.R(A)P}|CHEM1{[4aPEGMal]}|CHEM2{[4aPEGMal]}|CHEM3{[4aPEGMal]}|CHEM4{[4aPEGMal]}|CHEM5{[4aPEGMal]}$CHEM4,CHEM3,1:R2-1:R1|CHEM3,CHEM5,1:R2-1:R1|CHEM1,CHEM3,1:R4-1:R3|CHEM1,RNA1,1:R1-9:R2|CHEM3,CHEM2,1:R4-1:R3|CHEM2,RNA2,1:R1-9:R2$$$V2.0`
![image](https://github.com/user-attachments/assets/26cf79f5-6ae1-42d5-ade9-7aad8cda662a)
3. Select all monomers on the canvas and click Create Antisense Strand from context menu

**Actual behavior**
Nothing happens
Error in console:
![image](https://github.com/user-attachments/assets/fa7c8750-e875-4392-b2e6-373475c9ecca)

**Expected behavior**
Antisense chain created
![image](https://github.com/user-attachments/assets/2e592c01-acc9-42bc-a272-80f09d42b33e)

As per [requirement](https://github.com/epam/ketcher/issues/5678):

> 1.3. If multiple chains are selected and more than one satisfies the previous requirements, the "Create Antisense Strand" option should appear, and if clicked, multiple antisense chains are created.

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5678

**Comment by rrodionov91** [comment]
Fixed in https://github.com/epam/ketcher/pull/6099. Backmerged in https://github.com/epam/ketcher/pull/6111. Not linked because github does not allow to link more than 10 issues to PR

**Comment by AlexeyGirin** [comment]
Not fully fixed.
System doesn't crash but it create antisense chain for top chian but is shouldn't
Actual result:
![image](https://github.com/user-attachments/assets/47e0220c-c112-48c7-bfcb-84bca9687cf5)
Expected result:
![image](https://github.com/user-attachments/assets/2e592c01-acc9-42bc-a272-80f09d42b33e)

As per [requirement](https://github.com/epam/ketcher/issues/5678):

> 1.1. If there is a sugar in the backbone and it is connected to the a base via R3-R1, but the base is not a "sense base" form the table above, the "Create Antisense Strand" option should appear, but be disabled.
> 
>     For example, bases with natural analogue X from the library, or ambiguous bases not in the library.
>

**Comment by Drimodaren** [comment]
Closing Issue #6089

Besides the previously mentioned non-obvious behavior for users, there are several additional arguments that make this issue redundant or conflicting with existing mechanics.

1. Duplication of Logic from Issue #6088
	•	If #6088 already includes a mechanism to disable antisense strand creation for non-compatible fragments, then additional filtering in #6089 becomes redundant.
	•	In #6088, users immediately see that antisense strand creation is not possible, whereas in #6089, the filtering happens automatically and might be confusing.
	•	If both issues are implemented together, there could be UX conflicts because filtering would behave differently depending on the scenario.

2. Unclear Selection Logic for Antisense Strand
	•	If part of a structure allows antisense strand creation while another part does not, the user gets no explicit indication of why this is happening.
	•	This may create a perceived bug, where the user selects a full sequence but only a partial antisense strand is generated.
	•	Unlike disabling the button (as in #6088), silent filtering does not explain the reason for rejection, leading to potential confusion.

3. Increased Maintenance and Testing Complexity
	•	Implementing dynamic filtering of antisense strands during selection will increase code complexity, requiring additional verification checks.
	•	This introduces extra testing overhead, as various edge cases need to be considered where an antisense strand is only partially supported.
	•	Future changes in the logic of strand construction may introduce unexpected issues, as two mechanisms (selection filtering and direct strand blocking) will need to be maintained simultaneously.

4. Breaking Predictability in User Experience
	•	Ketcher is designed to follow a predictable workflow: if an antisense strand cannot be created, the button should be disabled.
	•	If the software automatically filters out incompatible segments during selection, users might not understand why certain regions were excluded.
	•	This contradicts UX expectations: users should make their own selection decisions, rather than having an automated filtering mechanism with no clear explanation.

Conclusion
	•	Issue #6089 overlaps with #6088, but it introduces less transparency for users.
	•	Filtering antisense strand support during selection may cause confusion, as users will not see why certain parts of the strand are excluded.
	•	Implementing this logic adds complexity to maintenance and testing, potentially creating UX inconsistencies.
	•	Ketcher already provides a mechanism to disable antisense strand creation when it is not possible (#6088), making additional filtering unnecessary.

📌 Closing issue #6089 is justified because its implementation would introduce UX inconsistencies, redundant functionality, and reduced predictability in the software’s behavior.

**Comment by AlexeyGirin** [comment]
Not fixed in proper way.

1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{R(A)P.[dR](A+C+G+U)P.R(A)P}|RNA2{R(A)P.[dR](A)P.R(A)P}|CHEM1{[4aPEGMal]}|CHEM2{[4aPEGMal]}|CHEM3{[4aPEGMal]}|CHEM4{[4aPEGMal]}|CHEM5{[4aPEGMal]}$CHEM4,CHEM3,1:R2-1:R1|CHEM3,CHEM5,1:R2-1:R1|CHEM1,CHEM3,1:R4-1:R3|CHEM1,RNA1,1:R1-9:R2|CHEM3,CHEM2,1:R4-1:R3|CHEM2,RNA2,1:R1-9:R2$$$V2.0`
![image](https://github.com/user-attachments/assets/26cf79f5-6ae1-42d5-ade9-7aad8cda662a)
3. Select all monomers on the canvas and click Create Antisense Strand from context menu

**Actual behavior**
System creates invalid antisense chain for top backbone and correct for bottom one

**Expected behavior**
As per [requirement 1.3](https://github.com/epam/ketcher/issues/5678): System does NOT create antisense chain for top backbone and correct for bottom one
BUT
If it is complicated - I would accept disabled antisense creation option if not a "sense base" present in the selection

**Comment by SefaBilgii** [comment]
This issue is not reproducible since antisense is disabled

<img width="2540" height="918" alt="Image" src="https://github.com/user-attachments/assets/ab552838-e52f-4c3f-a516-817f29da8a9c" />

Ketcher Version: 3.6.0-rc.1
OS: MacOs Sequoia Version 15.5
Browser : Chrome Version 138.0.7204.169
Indigo version 1.34.0-rc.1.0
