### ISSUE TITLE
System keeps antisense base layout and enumeration even after chain stops being antisense (and vice versa)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6102]
**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{[nC62r](T)P.[nC62r](G)P.[nC62r](C)P}|RNA2{R(A)P.R(C)P.R(G)P}$RNA1,RNA2,2:pair-2:pair$$$V2.0`
![image](https://github.com/user-attachments/assets/5928a9c8-f1c1-47ab-8c6e-59fb765933ec)
3. Remove hydrogen bond

**Actual behavior**
System keeps antisense base layout and enumeration even after chain stops being antisense
![image](https://github.com/user-attachments/assets/662ad115-dbb6-4ff7-b93b-a0b2cdbc91b5)

**Expected behavior**
System removes antisense base layout and change enumeration back to sense chain
![image](https://github.com/user-attachments/assets/9b77322e-65f1-4b50-947a-fb31396d6c51)

As per [requirement](https://github.com/epam/ketcher/issues/5678):

> 2.7. The antisense chain should be "flipped" in relation to the sense chain (see mockups) - bases of the new chain should be oriented in the opposite way, terminal indicators of the left-most sugar (associated with the base of a highest number) should be changed from 5' to 3' (or opposite) and/or of the left most amino acid from N to C (or opposite), and the numbering should go in the opposite direction.
> 
>     If the sense chain was oriented bases down, the antisense chain should be oriented bases up.
>     If the sense chain was oriented bases up, the antisense chain should be oriented bases down.
>     If the left most sugar/amino acid of the sense chain has a terminal indicator of 5'/N, then the left most sugar/amino acid of the antisense chain should have a terminal indicator of 3'/C.
>     If the left most sugar/amino acid of the sense chain has a terminal indicator of 3'/C, then the left most sugar/amino acid of the antisense chain should have a terminal indicator of 5'/N.
>     If the numbering of the sense chain increases from left to right, the numbering of the antisense chain should increase right to left.
>     If the numbering of the sense chain increases from right to left, the numbering of the antisense chain should increase left to right.

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5678

**Comment by rrodionov91** [comment]
Fixed in https://github.com/epam/ketcher/pull/6099. Backmerged in https://github.com/epam/ketcher/pull/6111. Not linked because github does not allow to link more than 10 issues to PR

**Comment by AlexeyGirin** [comment]
Not fully fixed.
Enumeration works correct in case of H-bond delete but chain layout remain.
![image](https://github.com/user-attachments/assets/4474dc9a-6076-4d14-9dce-fdb68b8ab8aa)
**Versions**
- Ketcher Version 2.28.0-rc.2 Build at 2024-12-10; 18:40:08
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- Win10
